# Generated by Django 6.0.4 on 2026-07-11 11:08

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='ticket_code',
            field=models.CharField(blank=True, default=app1.models.generate_short_ticket_code, max_length=20, unique=True),
        ),
    ]
