# Generated by Django 6.0.4 on 2026-07-10 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_profile_user_remove_event_available_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='ticket_code',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
